<?xml version="1.0" encoding="utf-8"?><Database Name="homework7" Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=homework7;Integrated Security=True;Pooling=False" SettingsObjectName="Lesson7_HomeWork_Task3.Properties.Settings" SettingsPropertyName="homework7ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Orders">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Movie" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateTime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoldBilets" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>